# Generated by Django 5.2.8 on 2025-11-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=255)),
                ('convidados', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('pix', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('horario', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='core.evento')),
            ],
            options={
                'verbose_name_plural': 'Pendências',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.usuario'),
        ),
    ]
