# Generated by Django 5.2.1 on 2025-11-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['horario']},
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='convidados',
            new_name='estimativa_convidados',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='status',
        ),
        migrations.AddField(
            model_name='atividade',
            name='feito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('acompanhantes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Recusado', 'Recusado')], default='Pendente', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to='core.evento')),
            ],
        ),
    ]
